name: Environment-Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          env:
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          echo "The client secret is: $CLIENT_SECRET"
          echo "The app service for the ${{ inputs.environment }} environment is: ${{ vars.APP_SERVICE }}"
          echo "The static website for the ${{ inputs.environment }} environment is: ${{ vars.STATIC_WEBSITE }}"
          echo "The GDW for the ${{ inputs.environment }} environment is: ${{ vars.GLOBAL_DATA_WAREHOUSE }}"

      - uses: actions/checkout@v6

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

