name: Environment-Test
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        - name: Echo_variables
          env:
            ENVIRONMENT_NAME: ${{ inputs.environment }} 
          run: |
            echo "The client secret is: ${{ secrets.CLIENT_SECRET }} "
            echo "The app service for the $ENVIRONMENT_NAME environment is: ${{ vars.APP_SERVICE }} "
            echo "The static website for the $ENVIRONMENT_NAME environment is: ${{ vars.STATIC_WEBSITE }}"
            echo "The GDW for the $ENVIRONMENT_NAME environment is: ${{ vars.GLOBAL_DATA_WAREHOUSE }}"



